Repository mitodl/ocw-hugo-projects, pull requests merged in 2022-04, with the labels that each got.

#155 add body text editing to resources
  ocw-course/ocw-studio.yaml
Labels: waiting on author

#157 add youtube description field and help text
  ocw-course/ocw-studio.yaml
Labels: waiting on author

#158 promo image required
  ocw-www/ocw-studio.yaml
Labels: waiting on author

#154 renamed testimonials to stories
  ocw-www/ocw-studio.yaml
Labels: waiting on author, blocked

#161 feat: embed resource added for ocw www
  ocw-www/ocw-studio.yaml
Labels: needs review

#163 use markdown widget on captions and credits
  ocw-course/ocw-studio.yaml
Labels: needs review
